---
- name: install apache
  package:
    name: apache2
    state: present

- name: copy index.html
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    mode: "0644"
  notify:
  - wait for open port

- name: start apache
  service:
    name: apache2
    state: started

